# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 05:41
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='视频标题', max_length=50, verbose_name='视频标题')),
                ('front_img', models.ImageField(help_text='封面图', max_length=200, upload_to='images/video/front/', verbose_name='封面图')),
                ('video_desc', DjangoUeditor.models.UEditorField(blank=True, default='', help_text='视频描述', null=True, verbose_name='视频描述')),
                ('video_url', models.URLField(default='', help_text='视频链接', verbose_name='视频链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '婚礼视频详情页',
                'verbose_name_plural': '婚礼视频详情页',
            },
        ),
        migrations.CreateModel(
            name='VideoLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='婚礼视频', help_text='该大类名称', max_length=40, verbose_name='该大类名称')),
                ('label', models.CharField(default='', help_text='标签', max_length=40, verbose_name='标签')),
                ('desc', models.TextField(default='', help_text='描述', verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '婚礼视频',
                'verbose_name_plural': '婚礼视频',
            },
        ),
    ]
