# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoinfo',
            name='label',
        ),
    ]
