# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='video_url',
            field=models.URLField(default='', help_text='视频链接', verbose_name='视频链接'),
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='video_info',
            field=models.TextField(default='', help_text='视频描述', max_length=200, verbose_name='视频描述'),
        ),
    ]
