# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:52
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_videoinfo_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='video_desc',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', help_text='视频描述', null=True, verbose_name='视频描述'),
        ),
    ]
