# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 20:24
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='区域名称', max_length=30, verbose_name='区域名称')),
                ('flag', models.ImageField(help_text='区域旗帜', max_length=200, upload_to='images/flags/', verbose_name='区域旗帜')),
                ('desc', models.TextField(default='', help_text='区域描述', verbose_name='区域描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '海外婚礼区域',
                'verbose_name_plural': '海外婚礼区域',
            },
        ),
        migrations.CreateModel(
            name='WeddingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='场地名称', max_length=50, verbose_name='场地名称')),
                ('desc', models.CharField(default='', help_text='场地简述', max_length=200, verbose_name='场地简述')),
                ('front_img', models.ImageField(help_text='封面图', max_length=200, upload_to='images/wedding/front/', verbose_name='封面图')),
                ('hotel_info', DjangoUeditor.models.UEditorField(default='', help_text='酒店介绍', verbose_name='酒店介绍')),
                ('place_info', DjangoUeditor.models.UEditorField(default='', help_text='场地信息', verbose_name='场地信息')),
                ('server_info', DjangoUeditor.models.UEditorField(default='', help_text='专业代订与其他服务', verbose_name='专业代订与其他服务')),
                ('book_info', DjangoUeditor.models.UEditorField(default='', help_text='预约须知', verbose_name='预约须知')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('area_name', models.ForeignKey(help_text='婚礼区域', on_delete=django.db.models.deletion.CASCADE, to='wedding.WeddingArea', verbose_name='婚礼区域')),
            ],
            options={
                'verbose_name': '海外婚礼详情页',
                'verbose_name_plural': '海外婚礼详情页',
            },
        ),
        migrations.CreateModel(
            name='WeddingLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='海外婚礼', help_text='该大类名称', max_length=40, verbose_name='该大类名称')),
                ('label', models.CharField(default='', help_text='标签', max_length=40, verbose_name='标签')),
                ('desc', models.TextField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '海外婚礼',
                'verbose_name_plural': '海外婚礼',
            },
        ),
        migrations.AddField(
            model_name='weddingarea',
            name='label',
            field=models.ForeignKey(help_text='海外婚礼', on_delete=django.db.models.deletion.CASCADE, to='wedding.WeddingLabel', verbose_name='海外婚礼'),
        ),
    ]
