# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingarea',
            name='label',
        ),
        migrations.AlterField(
            model_name='weddinginfo',
            name='area_name',
            field=models.ForeignKey(help_text='婚礼区域', on_delete=django.db.models.deletion.CASCADE, related_name='info', to='wedding.WeddingArea', verbose_name='婚礼区域'),
        ),
        migrations.AlterField(
            model_name='weddinginfoimage',
            name='name',
            field=models.ForeignKey(help_text='详情', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wedding.WeddingInfo', verbose_name='详情'),
        ),
    ]
