# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_auto_20171027_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weddinginfo',
            old_name='area_name',
            new_name='area_id',
        ),
    ]
