version: "3"
services:

  db:
    image: mysql
    container_name: db
    expose:
      - "3306"
    ports:
      - 3307:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - ./db:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=itlwedding
      - MYSQL_ROOT_PASSWORD=sd651134
    networks:
      - sentry

  itlwedding:
    build: ./itlwedding
    container_name: itlwedding
    command: uwsgi -i /itlwedding/conf/uwsgi.ini
    volumes:
      - ./itlwedding:/itlwedding
    ports:
      - 8000:8000
    links:
      - db:db
    networks:
      - sentry

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
<<<<<<< HEAD
      - "443:443" 
=======
      - "443:443"
>>>>>>> 006ff172ae77d4bc2f9d2b1cbb96d33719aa3670
    volumes:
      - ./itlwedding:/itlwedding
    links:
      - itlwedding:itlwedding
    networks:
      - sentry

networks:
    sentry:
        external: true
