# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 19:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='轮播图', max_length=200, upload_to='images/banner/', verbose_name='轮播图')),
                ('title', models.CharField(default='', help_text='标题', max_length=50, verbose_name='标题')),
                ('label', models.CharField(default='', help_text='标签', max_length=100, verbose_name='标签')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
    ]
