# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoinfo',
            name='label',
        ),
        migrations.AlterField(
            model_name='photoinfoimage',
            name='name',
            field=models.ForeignKey(help_text='详情', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='photo.PhotoInfo', verbose_name='详情'),
        ),
    ]
