# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:06
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnjoyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='客片标题', max_length=50, verbose_name='客片标题')),
                ('desc', models.CharField(blank=True, default='', help_text='客片简述', max_length=200, null=True, verbose_name='客片简述')),
                ('front_img', models.ImageField(help_text='封面图', max_length=200, upload_to='images/enjoy/front/', verbose_name='封面图')),
                ('enjoy_info', DjangoUeditor.models.UEditorField(default='', help_text='客片故事', verbose_name='客片故事')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '客片欣赏详情页',
                'verbose_name_plural': '客片欣赏详情页',
            },
        ),
        migrations.CreateModel(
            name='EnjoyInfoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/enjoy/img/')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('name', models.ForeignKey(help_text='详情', on_delete=django.db.models.deletion.CASCADE, to='enjoy.EnjoyInfo', verbose_name='详情')),
            ],
            options={
                'verbose_name': '客片详情页照片',
                'verbose_name_plural': '客片详情页照片',
            },
        ),
        migrations.CreateModel(
            name='EnjoyLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='客片欣赏', help_text='该大类名称', max_length=40, verbose_name='该大类名称')),
                ('label', models.CharField(default='', help_text='标签', max_length=40, verbose_name='标签')),
                ('desc', models.TextField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '客片欣赏',
                'verbose_name_plural': '客片欣赏',
            },
        ),
        migrations.AddField(
            model_name='enjoyinfo',
            name='label',
            field=models.ForeignKey(help_text='客片欣赏', on_delete=django.db.models.deletion.CASCADE, to='enjoy.EnjoyLabel', verbose_name='客片欣赏'),
        ),
    ]
