# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 15:47
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnjoyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enjoy_id', models.CharField(default='', help_text='详情页ID', max_length=50, verbose_name='详情页ID')),
                ('title', models.CharField(default='', help_text='客片标题', max_length=50, verbose_name='客片标题')),
                ('label', models.CharField(blank=True, default='', help_text='客片简述', max_length=200, null=True, verbose_name='客片简述')),
                ('front_img', models.ImageField(help_text='封面图', max_length=200, upload_to='images/enjoy/front/', verbose_name='封面图')),
                ('enjoy_info', DjangoUeditor.models.UEditorField(default='', help_text='客片故事', verbose_name='客片故事')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '客片欣赏详情页',
                'verbose_name': '客片欣赏详情页',
            },
        ),
        migrations.CreateModel(
            name='EnjoyLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', help_text='客片欣赏标签', max_length=40, verbose_name='客片欣赏标签')),
                ('desc', models.TextField(blank=True, default='', help_text='客片欣赏描述', null=True, verbose_name='客片欣赏描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '客片欣赏标签',
                'verbose_name': '客片欣赏标签',
            },
        ),
    ]
