# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enjoy', '0002_auto_20171026_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enjoyinfo',
            name='label',
        ),
    ]
