# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enjoy', '0003_remove_enjoyinfo_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enjoyinfoimage',
            name='name',
            field=models.ForeignKey(help_text='详情', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='enjoy.EnjoyInfo', verbose_name='详情'),
        ),
    ]
